In [38]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score,precision_score,confusion_matrix,classification_report, precision_recall_curve
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [48]:
cuisines_df = pd.read_csv('C:/Users/asger/Documents/GitHub/ML-For-Beginners/4-Classification/data/cuisines.csv')
cuisines_df.head()

,Unnamed: 0,cuisine,almond,angelica,anise,anise_seed,apple,apple_brandy,apricot,armagnac,...,whiskey,white_bread,white_wine,whole_grain_wheat_flour,wine,wood,yam,yeast,yogurt,zucchini
0,65,indian,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,66,indian,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,67,indian,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,68,indian,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,69,indian,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [40]:
cuisines_label_df = cuisines_df['cuisine']
cuisines_label_df.head()

0    indian
1    indian
2    indian
3    indian
4    indian
Name: cuisine, dtype: object

In [41]:
cuisines_feature_df = cuisines_df.drop(['Unnamed: 0', 'cuisine'], axis=1)
cuisines_feature_df.head()

,almond,angelica,anise,anise_seed,apple,apple_brandy,apricot,armagnac,artemisia,artichoke,...,whiskey,white_bread,white_wine,whole_grain_wheat_flour,wine,wood,yam,yeast,yogurt,zucchini
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [42]:
X_train, X_test, y_train, y_test = train_test_split(cuisines_feature_df, cuisines_label_df, test_size=0.3)

## Assignment: the original trained Adaboost classifier.

In [46]:
C = 10
classifiers = {
    'ADA': AdaBoostClassifier(n_estimators=100),

}

n_classifiers = len(classifiers)

for index, (name, classifier) in enumerate(classifiers.items()):
    classifier.fit(X_train, np.ravel(y_train))

    y_pred = classifier.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print("Accuracy (train) for %s: %0.1f%% " % (name, accuracy * 100))
    print(classification_report(y_test,y_pred))

Accuracy (train) for ADA: 65.9%
              precision    recall  f1-score   support

     chinese       0.52      0.37      0.44       131
      indian       0.89      0.83      0.86       187
    japanese       0.36      0.43      0.39        99
      korean       0.72      0.76      0.74       238
        thai       0.60      0.71      0.65        80

    accuracy                           0.66       735
   macro avg       0.62      0.62      0.61       735
weighted avg       0.66      0.66      0.66       735

Changing c does not affect the result of the Ada boost classifier, since Ada does not use c as a parameter. Therefore it will be removed from the next trainings.

The core principle of AdaBoost is to fit a sequence of weak learners (i.e., models that are only slightly better than random guessing, such as small decision trees) on repeatedly modified versions of the data. The predictions from all of them are then combined through a weighted majority vote (or sum) to produce the final prediction.

## Tweaking n_estimators

n_estimators describes the amount of weak learners being trained with. This should mean that if you increase the n_estimators, the accuracy would increase as well. This is however not the case. There is a trade-off between n_estimators and the learning rate of the algorithm, so if you increase the n_estimators too much, the accuracy will actually deminish.

In [50]:
classifiers = {
    'ADA1': AdaBoostClassifier(n_estimators=100,),
    'ADA2': AdaBoostClassifier(n_estimators=1000,)


}

n_classifiers = len(classifiers)

for index, (name, classifier) in enumerate(classifiers.items()):
    classifier.fit(X_train, np.ravel(y_train))

    y_pred = classifier.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print("Accuracy (train) for %s: %0.1f%% " % (name, accuracy * 100))
    print(classification_report(y_test,y_pred))

Accuracy (train) for ADA1: 65.9%
              precision    recall  f1-score   support

     chinese       0.52      0.37      0.44       131
      indian       0.89      0.83      0.86       187
    japanese       0.36      0.43      0.39        99
      korean       0.72      0.76      0.74       238
        thai       0.60      0.71      0.65        80

    accuracy                           0.66       735
   macro avg       0.62      0.62      0.61       735
weighted avg       0.66      0.66      0.66       735

Accuracy (train) for ADA2: 58.9%
              precision    recall  f1-score   support

     chinese       0.46      0.29      0.36       131
      indian       0.92      0.80      0.86       187
    japanese       0.32      0.70      0.44        99
      korean       0.77      0.50      0.61       238
        thai       0.48      0.71      0.58        80

    accuracy                           0.59       735
   macro avg       0.59      0.60      0.57       735
weighted avg       0.66      0.59      0.60       735

As seen above, the accuracy decreased as the number of estimators increased too high.

## Tweaking learning rate

When using ADA boost the learning rate is by default set to 1.0. But we can change it.

In [59]:
classifiers = {
    'ADA1': AdaBoostClassifier(n_estimators=100, learning_rate=1.0),
    'ADA2': AdaBoostClassifier(n_estimators=100, learning_rate=0.5),
}

n_classifiers = len(classifiers)

for index, (name, classifier) in enumerate(classifiers.items()):
    classifier.fit(X_train, np.ravel(y_train))

    y_pred = classifier.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print("Accuracy (train) for %s: %0.1f%% " % (name, accuracy * 100))
    print(classification_report(y_test,y_pred))

Accuracy (train) for ADA1: 65.9%
              precision    recall  f1-score   support

     chinese       0.52      0.37      0.44       131
      indian       0.89      0.83      0.86       187
    japanese       0.36      0.43      0.39        99
      korean       0.72      0.76      0.74       238
        thai       0.60      0.71      0.65        80

    accuracy                           0.66       735
   macro avg       0.62      0.62      0.61       735
weighted avg       0.66      0.66      0.66       735

Accuracy (train) for ADA2: 70.1%
              precision    recall  f1-score   support

     chinese       0.53      0.67      0.59       131
      indian       0.90      0.78      0.83       187
    japanese       0.52      0.33      0.41        99
      korean       0.74      0.82      0.77       238
        thai       0.68      0.68      0.68        80

    accuracy                           0.70       735
   macro avg       0.67      0.66      0.66       735
weighted avg       0.71      0.70      0.70       735

As seen above, by decreasing the learning rate, we can increase the accuracy of the algorithm.